spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qq
    username: root
    password: 123456789
    type: com.alibaba.druid.pool.DruidDataSource

thymeleaf:
  cache: false

server:
  port: 8080
